version: "3.4"
services:
  smartiot-config:
    build: https://github.com/AntorFr/SmartIoT-ConfigServer.git
    restart: unless-stopped
    volumes:
      - ./configs:/app/data/configs
      - ./discovery:/app/data/discovery
      - ./firmwares:/app/data/firmwares
      - ./settings:/app/data/settings
    networks:
      - backend-net

networks:
  backend-net:
    external:
      name: backend-net