version: '3.4'

services:
  smartiotconfigserver:
    image: smartiotconfigserver
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./configs:/app/configs
      - ./discovery:/app/discovery
      - ./firmwares:/app/firmwares
